import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { BackgroundBoxesDemo } from "@/components/Background";
import NavbarDemo from "@/components/Navbar";
import { HeroParallaxDemo } from "@/components/Hero";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarDemo/>
        <BackgroundBoxesDemo/>
        <HeroParallaxDemo/>
        {children}
        </body>
    </html>
  );
}
